### ISSUE TITLE
pstat throws error parsing empty qstat output

### ISSUE THREAD

**Issue by gdevenyi** [sseemayer/qstat-pretty#11]
If you have an empty qstat -x, pstat tried to parse it anyways and throws an error.

```
Traceback (most recent call last):
  File "./pstat", line 139, in <module>
    main()
  File "./pstat", line 112, in main
    jobs = parser.parse(source(parser, args))
  File "/bg01/homescinet/m/mchakrav/gdevenyi/bin/qstat-pretty/qstatpretty/parser/torque.py", line 58, in parse
    xml = ET.parse(f)
  File "<string>", line 45, in parse
  File "<string>", line 32, in parse
SyntaxError: no element found: line 1, column 0
```

Not sure the right place to do this, one would be:
https://github.com/sseemayer/qstat-pretty/blob/master/qstatpretty/parser/torque.py#L58
and
https://github.com/sseemayer/qstat-pretty/blob/master/qstatpretty/parser/gridengine.py#L51

Need to check the length of `f` maybe and return no jobs if empty?

**Comment by sseemayer** [comment]
Sorry about the troubles! It's difficult to maintain qstat-pretty with resource managers that I'm not currently having access to after moving institutes. Are you saying the output of `qstat -x` is completely empty for you?

Your suggestion for catching this problem sounds good to me and returning an empty job array should work :+1:.

**Comment by gdevenyi** [comment]
No problem, I just fixed this in my own cluster software ;) https://github.com/pipitone/qbatch/commit/7fd1d760a57c381cbd9fe3c29037d9a4518d0c0a

Thanks for the nice software, I use it on SGE and PBS and it really helps.

**Comment by muppetjones** [comment]
I don't think the problem is Torque:

```
[10:18:19 2] $ pstat -x
Torque Resource Manager
0 jobs total
```

But thanks for catching and fixing the issue!

**Comment by gdevenyi** [comment]
@muppetjones what's your output of `qstat -x`? Is it blank? or something else?

**Comment by muppetjones** [comment]
It's blank. What is yours?

**Comment by gdevenyi** [comment]
Also, blank. Interesting. I wonder if the internals of parser changed between versions.

**Comment by muppetjones** [comment]
Could be. I just checked, and I don't think I've pulled since I added the Torque parser; however, the changes since then don't seem to be part of the problem (at least based on the error from above).

Either way, thanks for fixing the issue! I'll keep an eye on it and see if I can't get it to trigger on my end.

**Comment by gdevenyi** [comment]
I've also reported this as a bug to Torque, as SGE does the "right thing (tm)" and gives a properly formatted XML with no jobs in it.
