### ISSUE TITLE
Piping pstat output in any way crashes pstat

### ISSUE THREAD

**Issue by gdevenyi** [sseemayer/qstat-pretty#12]
If I want to use less, or grep on a pstat output, I find that pstat crashes with something about unicode:

```
> pstat | less
Traceback (most recent call last):
  File "/home/cic/devgab/bin/qstat-pretty/pstat", line 139, in <module>
    main()
  File "/home/cic/devgab/bin/qstat-pretty/pstat", line 118, in main
    qstatpretty.pretty.pretty_table(jobs, parser.table_columns, table_algorithm=ttyresize.TABLE_ALGORITHMS[opt.table_algorithm], delimiters=ttytable.DELIMITERS[opt.delimiters])
  File "/home/cic/devgab/bin/qstat-pretty/qstatpretty/pretty.py", line 23, in pretty_table
    print(ttytable.pretty_table(tbl, table_format, delimiters=delimiters))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 235-240: ordinal not in range(128)
```

**Comment by gdevenyi** [comment]
Problem was actually PR #15
