### ISSUE TITLE
ImportError: No module named 'qstatpretty.ttyutil.resize'

### ISSUE THREAD

**Issue by basnijholt** [sseemayer/qstat-pretty#16]
```
[basnijholt@hpc05:~]$ pip install https://github.com/sseemayer/qstat-pretty/archive/master.zip -U
Collecting https://github.com/sseemayer/qstat-pretty/archive/master.zip
  Downloading https://github.com/sseemayer/qstat-pretty/archive/master.zip
Installing collected packages: qstat-pretty
  Found existing installation: qstat-pretty 0.1.0
    Uninstalling qstat-pretty-0.1.0:
      Successfully uninstalled qstat-pretty-0.1.0
  Running setup.py install for qstat-pretty ... done
Successfully installed qstat-pretty-0.1.0



[basnijholt@hpc05:~]$ pstat
Traceback (most recent call last):
  File "/home/basnijholt/anaconda3/bin/pstat", line 7, in <module>
    import qstatpretty.pretty
  File "/home/basnijholt/anaconda3/lib/python3.5/site-packages/qstatpretty/pretty.py", line 2, in <module>
    import qstatpretty.ttyutil.resize as ttyresize
ImportError: No module named 'qstatpretty.ttyutil.resize'
```

**Comment by basnijholt** [comment]
This issue is fixed by pull request #17

**Comment by pwwang** [comment]
This still happends:
```
 >  pip install https://github.com/sseemayer/qstat-pretty/archive/master.zip -U  
Collecting https://github.com/sseemayer/qstat-pretty/archive/master.zip
  Downloading https://github.com/sseemayer/qstat-pretty/archive/master.zip
     | 30kB 1.1MB/s
Installing collected packages: qstat-pretty
  Running setup.py install for qstat-pretty ... done
Successfully installed qstat-pretty-0.1.0

 >  pstat            
Traceback (most recent call last):
  File "/data2/junwenwang/shared/tools/miniconda2/bin/pstat", line 7, in <module>
    import qstatpretty.pretty
  File "/data2/junwenwang/shared/tools/miniconda2/lib/python2.7/site-packages/qstatpretty/pretty.py", line 2, in <module>
    import qstatpretty.ttyutil.resize as ttyresize
ImportError: No module named resize

```

**Comment by pwwang** [comment]
Oh, PR #17 is not merged yet.

**Comment by pwwang** [comment]
For guys also encounter this, before PR #17 is merged, you can do this:
```bash
git clone https://github.com/sseemayer/qstat-pretty.git
cd qstat-pretty
git fetch origin pull/17/head:pr-17
git checkout pr-17
python setup.py install
```
