### ISSUE TITLE
Error on Torque cluster

### ISSUE THREAD

**Issue by basnijholt** [sseemayer/qstat-pretty#9]
I installed it via pip for Python 3.5 and added the config file

This happens:

```
pstat
Traceback (most recent call last):
  File "/home/basnijholt/anaconda3/bin/pstat", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/basnijholt/Dropbox/src/qstatpretty/pstat", line 139, in <module>
    main()
  File "/home/basnijholt/Dropbox/src/qstatpretty/pstat", line 112, in main
    jobs = parser.parse(source(parser, args))
TypeError: parse() missing 1 required positional argument: 'f'
```

**Comment by sseemayer** [comment]
Sorry about that - It's difficult to maintain different grid system flavors when I don't have access to them :)

I've just pushed a possible fix for this, can you update and try again? Thanks!

**Comment by basnijholt** [comment]
Thanks for the quick response!
However this happens now:

```
Traceback (most recent call last):
  File "/home/basnijholt/anaconda3/bin/pstat", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/basnijholt/src/qstatpretty/pstat", line 139, in <module>
    main()
  File "/home/basnijholt/src/qstatpretty/pstat", line 112, in main
    jobs = parser.parse(source(parser, args))
  File "/home/basnijholt/src/qstatpretty/qstatpretty/parser/torque.py", line 64, in parse
    jobs = [TorqueParser.process_job(job) for job in job_list]
  File "/home/basnijholt/src/qstatpretty/qstatpretty/parser/torque.py", line 64, in <listcomp>
    jobs = [TorqueParser.process_job(job) for job in job_list]
  File "/home/basnijholt/src/qstatpretty/qstatpretty/parser/torque.py", line 36, in process_job
    job[key] = f(val)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'xml.etree.ElementTree.Element'
```

**Comment by sseemayer** [comment]
Can you send me a dump of your `qstat -x` output, e.g. using a gist or pastebin?

**Comment by basnijholt** [comment]
[Here it is](https://gist.github.com/basnijholt/98023eb9a01ed9c7f320)

**Comment by sseemayer** [comment]
Thanks for the test data! - seems like the last refactor left behind some bugs. What happens if you update and re-run now?

**Comment by basnijholt** [comment]
Great, now it works!

Could I easily adjust the script to kill all jobs by a user (me)?

**Comment by sseemayer** [comment]
Awesome! qstat-pretty is designed only for reading access to the cluster status command. It would probably be doable to add a feature like that but will involve some work. I'd be happy to accept a pull request though :) 

If you want to add support, [here is where the qstat command is constructed to ask for jobs](https://github.com/sseemayer/qstat-pretty/blob/master/qstatpretty/parser/torque.py#L74-L76) and [here is where these commands are executed locally or via SSH](https://github.com/sseemayer/qstat-pretty/blob/master/qstatpretty/source.py#L14-L41).
